// =============================================================================
// Generated by BotForge v0.2 — DO NOT EDIT MANUALLY
// Bot    : mini_rover
// Target : Arduino
// =============================================================================

#include <Arduino.h>
#include <NewPing.h>

#define MAX_DISTANCE 200

// ---------------------------------------------------------------------------
// Speed helper
// DSL uses speed as a percentage (0–100).
// Arduino analogWrite() expects PWM (0–255).
// ---------------------------------------------------------------------------
int normalizeSpeed(int pct) {
    if (pct <= 0)   return 0;
    if (pct >= 100) return 255;
    return (pct * 255) / 100;
}

NewPing front(7, 8, MAX_DISTANCE);



// ---------------------------------------------------------------------------
// Wheels — differential drive wrapper
// ---------------------------------------------------------------------------
class Wheels {
public:
    Wheels(int lFwd, int lRev, int rFwd, int rRev)
        : lFwd(lFwd), lRev(lRev), rFwd(rFwd), rRev(rRev) {}

    void forward(int pwm) {
        analogWrite(lFwd, pwm); analogWrite(rFwd, pwm);
        analogWrite(lRev, 0);   analogWrite(rRev, 0);
    }
    void backward(int pwm) {
        analogWrite(lRev, pwm); analogWrite(rRev, pwm);
        analogWrite(lFwd, 0);   analogWrite(rFwd, 0);
    }
    void turnLeft(int pwm) {
        analogWrite(lRev, pwm); analogWrite(rFwd, pwm);
        analogWrite(lFwd, 0);   analogWrite(rRev, 0);
    }
    void turnRight(int pwm) {
        analogWrite(lFwd, pwm); analogWrite(rRev, pwm);
        analogWrite(lRev, 0);   analogWrite(rFwd, 0);
    }
    void stop() {
        analogWrite(lFwd, 0); analogWrite(lRev, 0);
        analogWrite(rFwd, 0); analogWrite(rRev, 0);
    }

private:
    int lFwd, lRev, rFwd, rRev;
};

Wheels wheels(5, 6, 9, 10);

// ---------------------------------------------------------------------------
// Arduino entry points
// ---------------------------------------------------------------------------
void setup() {
}

void loop() {
    if (front.ping_cm() < 20) {
        wheels.turnLeft(normalizeSpeed(50));
    } else {
        wheels.forward(normalizeSpeed(80));
    }
}