// =============================================================================
// Generated by BotForge — DO NOT EDIT MANUALLY
// Bot: mini_rover
// Target: Arduino
// =============================================================================

#include <Arduino.h>
#include <NewPing.h>

#define MAX_DISTANCE 200

NewPing front(7, 8, MAX_DISTANCE);


// ---------------------------------------------------------------------------
// Wheels class
// ---------------------------------------------------------------------------
class Wheels {
public:
    Wheels(int leftPin1, int leftPin2, int rightPin1, int rightPin2)
        : leftPin1(leftPin1), leftPin2(leftPin2),
          rightPin1(rightPin1), rightPin2(rightPin2) {}

    void forward(int speed) {
        analogWrite(leftPin1, speed);
        analogWrite(rightPin1, speed);
        analogWrite(leftPin2, 0);
        analogWrite(rightPin2, 0);
    }

    void backward(int speed) {
        analogWrite(leftPin2, speed);
        analogWrite(rightPin2, speed);
        analogWrite(leftPin1, 0);
        analogWrite(rightPin1, 0);
    }

    void turnLeft(int speed) {
        analogWrite(leftPin2, speed);
        analogWrite(rightPin1, speed);
        analogWrite(leftPin1, 0);
        analogWrite(rightPin2, 0);
    }

    void turnRight(int speed) {
        analogWrite(leftPin1, speed);
        analogWrite(rightPin2, speed);
        analogWrite(leftPin2, 0);
        analogWrite(rightPin1, 0);
    }

    void stop() {
        analogWrite(leftPin1, 0);
        analogWrite(leftPin2, 0);
        analogWrite(rightPin1, 0);
        analogWrite(rightPin2, 0);
    }

private:
    int leftPin1, leftPin2, rightPin1, rightPin2;
};

Wheels wheels(5, 6, 9, 10);

// ---------------------------------------------------------------------------
// Arduino entry points
// ---------------------------------------------------------------------------
void setup() {
}

void loop() {
    if (front.ping_cm() < 20) {
        wheels.turnLeft(50);
    } else {
        wheels.forward(80);
    }
}