// =============================================================================
// Generated by BotForge — DO NOT EDIT MANUALLY
// Bot: servo_bot
// Target: Arduino
// =============================================================================

#include <Arduino.h>
#include <NewPing.h>
#include <Servo.h>

#define MAX_DISTANCE 200

NewPing front(7, 8, MAX_DISTANCE);

Servo arm;


// ---------------------------------------------------------------------------
// Arduino entry points
// ---------------------------------------------------------------------------
void setup() {
    arm.attach(3);
}

void loop() {
    if (front.ping_cm() < 15) {
        arm.write(0);
    } else {
        arm.write(90);
    }
}